#!/bin/lua

require("utils").using("utils")
using("dataframes")
using("database")
using("paths")
using("dates")
using("user")

script_path = debug.getinfo(1, "S").source:sub(2)
add_to_path(script_path, "src")

using("bx_utils")
using("init")
using("note")
using("task")
using("update")
using("sql")
using("prettyprint")

local function print_help()
    help_str = [[
Usage: brex < command > < arguments >

       brex init < --vault >
       brex note < add | edit | last >
       brex task < list | add | done | delay | last >
       brex sql < query >
       brex update < file >
    ]]

    print(help_str)
end

local function main()
    local command_parser = {
        ["init"] = {
            default = init_bx,
            ["--vault"] = init_bx_with_vault
        },
        ["note"] = {
            default = todays_note,
            add = take_note,
            edit = edit_note,
            last = last_notes
        },
        ["task"] = {
            default = add_task,
            add = add_task,
            list = list_tasks,
            done = mark_done,
            delay = delay_due,
            last = last_done
        },
        ["update"] = {
            default = update_from_vault,
            ["file"] = update_note_from_file
            
        },
        ["sql"] = {
            default = sqlite_shell,
            ["query"] = sqlite_query
        }
    }

    if length(arg) == 0 then
        print_help()
        return
    end

    local command = arg[1]
    local argument = arg[2] or "default"

    local command_config = command_parser[command]
    if not command_config then
        print("'" .. command .. "' is not a valid command\n")
        print_help()
        return
    end

    local func = command_config[argument]
    if not func then
        print("'" .. command .. "' got invalid argument '" .. argument .. "'\n")
        print_help()
        return
    end

    if command ~= "init" then
        local brain_file = get_brain_file()
        func(brain_file)
    else
        func()
    end
end

-- run program
main()
