#!/bin/lua

local function get_parent_dir(path)
    path = path:gsub("[\\/]+$", "")
    local parent_dir = path:match("(.*/)")
    return parent_dir
end

local function get_script_dir()
    local script_path = debug.getinfo(1, "S").source:sub(2)
    local script_dir = get_parent_dir(script_path)
    return script_dir
end

local bx_path = get_script_dir()
local project_dir = get_parent_dir(bx_path)
local lua_utils_path = project_dir .. "lua-utils/src/"
print(bx_path)
print(lua_utils_path)

package.path = bx_path .. "?.lua;" .. package.path
package.path = lua_utils_path .. "?.lua;" .. package.path

require("utils").using("utils")
using("dataframes")
using("bx_utils")
using("init")
using("note")
using("todo")

local function print_help()
	print("Usage: brex < command > < arguments >")
    print("")
    print("Usage: brex init < --vault >")
	print("Usage: brex note < add >")
	print("Usage: brex todo < list | add | done >")
end

local function main()
    local command_parser = {
        ["init"] = {
            default = init_bx,
            ["--vault"] = init_bx_with_vault
        },
        ["note"] = {
            add = take_note,
            connect = connect_notes
        },
        ["todo"] = {
            add = add_task,
            list = list_tasks,
            done = mark_done
        }
    }

    local brain_file = get_brain_file()
    print(brain_file)

    local func
    if length(arg) == 0 then
        print("missing command\n")
        print_help()
    elseif length(arg) == 1 then
	    local command = arg[1]
        if command == "init" then
            func = command_parser[command]["default"]
            func()
        elseif occursin(command, command_parser) then
            print("'" .. command .. "' is missing arguments\n")
            print_help()
        else
            print("'" .. command .. "' is not a valid command\n")
            print_help()
        end
    elseif length(arg) == 2 then
        local command = arg[1]
        local argument = arg[2]
	    if command_parser[command] then
            if command_parser[command][argument] then
                func = command_parser[command][argument]
                func(brain_file)
            else
                print("'" .. command .. "' got invalid argument '" .. argument .. "'\n")
                print_help()
            end
        else
            print("'" .. command .. "' is not a valid command\n")
            print_help()
        end
    else
        print("too many arguments given\n")
        print_help()
    end
end

-- run program
main()
